### ISSUE TITLE
A qlog file formated with json-seq

### ISSUE THREAD

**Issue by nixwl** [quiclog/qvis#82]
- I have got  a qlog file（it‘s JSON-SEQ format），So I want to convert JSON-SEQ to JSON. Because website's qlog example supported JSON.
- How can I slove this problem, any tools or function ?

**Comment by rmarx** [comment]
Hey @nixwl,

qvis should just support the JSON-SEQ format as well, so there should be no need to convert to JSON (as such, there are also no existing tools for this (though it should be easy enough to write one, it's quite simple)).

Can you share an example file and the implementation you're using maybe? If you're actually getting errors loading the file into qvis, which errors?

**Comment by nixwl** [comment]
hi， I can import  JSON-SEQ  format qlog file to website，but I found  that:
![image](https://github.com/quiclog/qvis/assets/80773211/67ef8ddd-3590-449d-864d-18084e1b3b90)


This qlog file record client download file form a QUIC file server（the QUIC server uses [TQUIC](https://github.com/Tencent/tquic/tree/develop/tools/src/bin)）

This is the client  qlog info:
![image](https://github.com/quiclog/qvis/assets/80773211/c2675eb2-8bd6-46ad-a3ef-44440c6ffd5e)

and client qlog file is here:    [qlog_c.txt](https://github.com/quiclog/qvis/files/14060815/qlog_c.txt)

I don't know if my qlog file has any problems, but  the connection may be established,  and file download function had well worked

**Comment by nixwl** [comment]
I take that issue to [TQUIC ](https://github.com/Tencent/tquic/blob/develop/tools/script/tquic_qvis.sh)developer few days before. And they make a scipt to covert JSON-SEQ to JSON, So I try it recently.

This is the result:(converted qlog file is here: [qlog_c.qlog.json](https://github.com/quiclog/qvis/files/14060998/qlog_c.qlog.json))
 
![image](https://github.com/quiclog/qvis/assets/80773211/cf7ea33f-6816-47c1-bda0-96de9e8face7)

**Comment by rmarx** [comment]
So it turns out that the JSON-SEQ file you use isn't actually proper JSON-SEQ as per the qlog spec :) 
It just uses a \n newline character to separate the records, but that's not enough: they also need to be separated by the special RS (record separator, 0x1E) character (see also https://www.ietf.org/archive/id/draft-ietf-quic-qlog-main-schema-07.html#format-json-seq).

Since they don't do that, qvis can't properly parse the file and shows an error in the JavaScript console (I agree it's confusing that it does show a green popup in the webpage UI, pretending that it did load correctly ;)).

So, the solution here is to ask the TQUIC maintainers to either output proper JSON-SEQ as per the spec, or for you to use their script to convert to JSON, which indeed does seem to work as expected. 

(I will keep this issue open to remind myself to one day properly show a red popup with an error message if this error occurs again, rather than people having to open the JavaScript console in the developer tools).
